name: create-release
on:
  push: 
    tags:
      - "v*"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
      - name: Prepare Folder For Packaging
        run: |
          mkdir -p "Assets/VRLabs/World Constraint"
          ls | grep -v "Assets" | xargs -i{} mv {} "Assets/VRLabs/World Constraint"
          echo -e "fileFormatVersion: 2\nguid: 652a1ba5b00554143bc9a76307dbc4e8\nfolderAsset: yes\nDefaultImporter:\n  externalObjects: {}\n  userData: \n  assetBundleName: \n  assetBundleVariant: " > "Assets/VRLabs.meta"
          echo -e "fileFormatVersion: 2\nguid: bf82f1f4eac86b14082325c8d3ac728c\nfolderAsset: yes\nDefaultImporter:\n  externalObjects: {}\n  userData: \n  assetBundleName: \n  assetBundleVariant: " > "Assets/VRLabs/World Constraint.meta"
          find "Assets/" -name \*.meta ! -name "Media.meta" -not -path "Assets/VRLabs/World Constraint/Media/*" > package

      - name: Create UnityPackage
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'World_Constraint_${{ env.SOURCE_TAG }}.unitypackage'
          include-files: package
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "World Constraint ${{ env.SOURCE_TAG }}"
          files: |
            World_Constraint_${{ env.SOURCE_TAG }}.unitypackage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
